# Generated by Django 4.1.6 on 2023-02-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
