# Generated by Django 4.1.6 on 2023-02-22 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_perfilusuario_registra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'permissions': [('can_view_users_list', 'Can view users list')]},
        ),
    ]
