# Generated by Django 4.1.6 on 2023-02-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_perfilusuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'permissions': [('can_view_users_list', 'Can view users list'), ('cambiar_credito', 'Cambiar credito de cliente')]},
        ),
    ]
