# Generated by Django 4.1.6 on 2023-03-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_delete_tipousuario_rename_user_perfilusuario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='creditos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
